# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/microblaze_test/Arty-A7-100-Master.xdc

# Block Designs: bd/microblaze_test/microblaze_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_test || ORIG_REF_NAME==microblaze_test} -quiet] -quiet

# IP: bd/microblaze_test/ip/microblaze_test_clk_wiz_0_0/microblaze_test_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_test_clk_wiz_0_0 || ORIG_REF_NAME==microblaze_test_clk_wiz_0_0} -quiet] -quiet

# IP: bd/microblaze_test/ip/microblaze_test_reset_inv_0_0/microblaze_test_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_test_reset_inv_0_0 || ORIG_REF_NAME==microblaze_test_reset_inv_0_0} -quiet] -quiet

# IP: bd/microblaze_test/ip/microblaze_test_microblaze_0_0/microblaze_test_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_test_microblaze_0_0 || ORIG_REF_NAME==microblaze_test_microblaze_0_0} -quiet] -quiet

# IP: bd/microblaze_test/ip/microblaze_test_dlmb_v10_0/microblaze_test_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_test_dlmb_v10_0 || ORIG_REF_NAME==microblaze_test_dlmb_v10_0} -quiet] -quiet

# IP: bd/microblaze_test/ip/microblaze_test_ilmb_v10_0/microblaze_test_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_test_ilmb_v10_0 || ORIG_REF_NAME==microblaze_test_ilmb_v10_0} -quiet] -quiet

# IP: bd/microblaze_test/ip/microblaze_test_dlmb_bram_if_cntlr_0/microblaze_test_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_test_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblaze_test_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microblaze_test/ip/microblaze_test_ilmb_bram_if_cntlr_0/microblaze_test_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_test_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblaze_test_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microblaze_test/ip/microblaze_test_lmb_bram_0/microblaze_test_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_test_lmb_bram_0 || ORIG_REF_NAME==microblaze_test_lmb_bram_0} -quiet] -quiet

# IP: bd/microblaze_test/ip/microblaze_test_mdm_1_0/microblaze_test_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_test_mdm_1_0 || ORIG_REF_NAME==microblaze_test_mdm_1_0} -quiet] -quiet

# IP: bd/microblaze_test/ip/microblaze_test_rst_clk_wiz_0_100M_0/microblaze_test_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_test_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==microblaze_test_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/microblaze_test/ip/microblaze_test_axi_uartlite_0_0/microblaze_test_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_test_axi_uartlite_0_0 || ORIG_REF_NAME==microblaze_test_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/microblaze_test/ip/microblaze_test_microblaze_0_axi_periph_0/microblaze_test_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_test_microblaze_0_axi_periph_0 || ORIG_REF_NAME==microblaze_test_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/microblaze_test/ip/microblaze_test_axi_gpio_0_0/microblaze_test_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_test_axi_gpio_0_0 || ORIG_REF_NAME==microblaze_test_axi_gpio_0_0} -quiet] -quiet

# IP: bd/microblaze_test/ip/microblaze_test_axi_gpio_0_1/microblaze_test_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_test_axi_gpio_0_1 || ORIG_REF_NAME==microblaze_test_axi_gpio_0_1} -quiet] -quiet

# IP: bd/microblaze_test/ip/microblaze_test_xbar_0/microblaze_test_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_test_xbar_0 || ORIG_REF_NAME==microblaze_test_xbar_0} -quiet] -quiet

# XDC: /pool/xuyi/axi-dma-engine/microblaze_test/microblaze_test.gen/sources_1/bd/microblaze_test/microblaze_test_ooc.xdc
