set_property SRC_FILE_INFO {cfile:C:/Users/laptop/Desktop/axi-dma-engine/vivado/sys_constraints.xdc rfile:../../../../axi-dma-engine/vivado/sys_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3      [get_ports sys_clock]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C2      [get_ports reset]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks clk_out1_design_1_clk_wiz_1_0] -to [get_ports usb_uart_txd]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports usb_uart_rxd] -to [get_clocks clk_out1_design_1_clk_wiz_1_0]
