# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /pool/xuyi/axi-dma-engine/microblaze_test/microblaze_test.srcs/sources_1/bd/microblaze_test/ip/microblaze_test_lmb_bram_0/microblaze_test_lmb_bram_0.xci
# IP: The module: 'microblaze_test_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /pool/xuyi/axi-dma-engine/microblaze_test/microblaze_test.gen/sources_1/bd/microblaze_test/ip/microblaze_test_lmb_bram_0/microblaze_test_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_test_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /pool/xuyi/axi-dma-engine/microblaze_test/microblaze_test.srcs/sources_1/bd/microblaze_test/ip/microblaze_test_lmb_bram_0/microblaze_test_lmb_bram_0.xci
# IP: The module: 'microblaze_test_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /pool/xuyi/axi-dma-engine/microblaze_test/microblaze_test.gen/sources_1/bd/microblaze_test/ip/microblaze_test_lmb_bram_0/microblaze_test_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_test_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
